/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.google.re2fj.wrapper;

public class Int2StringMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Int2StringMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Int2StringMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        re2fjJNI.delete_Int2StringMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Int2StringMap() {
    this(re2fjJNI.new_Int2StringMap__SWIG_0(), true);
  }

  public Int2StringMap(Int2StringMap arg0) {
    this(re2fjJNI.new_Int2StringMap__SWIG_1(Int2StringMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return re2fjJNI.Int2StringMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return re2fjJNI.Int2StringMap_empty(swigCPtr, this);
  }

  public void clear() {
    re2fjJNI.Int2StringMap_clear(swigCPtr, this);
  }

  public String get(int key) {
    return re2fjJNI.Int2StringMap_get(swigCPtr, this, key);
  }

  public void set(int key, String x) {
    re2fjJNI.Int2StringMap_set(swigCPtr, this, key, x);
  }

  public void del(int key) {
    re2fjJNI.Int2StringMap_del(swigCPtr, this, key);
  }

  public boolean has_key(int key) {
    return re2fjJNI.Int2StringMap_has_key(swigCPtr, this, key);
  }

}
