/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.google.re2fj.wrapper;

public class IntVectorPointer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntVectorPointer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVectorPointer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        re2fjJNI.delete_IntVectorPointer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntVectorPointer() {
    this(re2fjJNI.new_IntVectorPointer(), true);
  }

  public long Size() {
    return re2fjJNI.IntVectorPointer_Size(swigCPtr, this);
  }

  public int Value(long index) {
    return re2fjJNI.IntVectorPointer_Value(swigCPtr, this, index);
  }

  public IntVector Pointer() {
    long cPtr = re2fjJNI.IntVectorPointer_Pointer(swigCPtr, this);
    return (cPtr == 0) ? null : new IntVector(cPtr, false);
  }

}
