/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.google.re2fj.wrapper;

public class re2fjJNI {
  public final static native long Re2Options_GetOption(long jarg1, Re2Options jarg1_);
  public final static native boolean Re2Options_utf8(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_utf8(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_posix_syntax(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_posix_syntax(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_longest_match(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_longest_match(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_log_errors(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_log_errors(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native int Re2Options_max_mem(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_max_mem(long jarg1, Re2Options jarg1_, int jarg2);
  public final static native boolean Re2Options_literal(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_literal(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_never_nl(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_never_nl(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_dot_nl(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_dot_nl(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_never_capture(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_never_capture(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_case_sensitive(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_case_sensitive(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_perl_classes(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_perl_classes(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_word_boundary(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_word_boundary(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native boolean Re2Options_one_line(long jarg1, Re2Options jarg1_);
  public final static native void Re2Options_set_one_line(long jarg1, Re2Options jarg1_, boolean jarg2);
  public final static native void Re2Options_Copy(long jarg1, Re2Options jarg1_, long jarg2, Re2Options jarg2_);
  public final static native long new_Re2Options();
  public final static native void delete_Re2Options(long jarg1);
  public final static native long new_Re2Set(long jarg1, Re2Options jarg1_, int jarg2);
  public final static native void delete_Re2Set(long jarg1);
  public final static native int Re2Set_Add(long jarg1, Re2Set jarg1_, String jarg2, long jarg3);
  public final static native boolean Re2Set_Compile(long jarg1, Re2Set jarg1_);
  public final static native boolean Re2Set_Match(long jarg1, Re2Set jarg1_, String jarg2, long jarg3, IntVector jarg3_);
  public final static native long new_IntVectorPointer();
  public final static native void delete_IntVectorPointer(long jarg1);
  public final static native long IntVectorPointer_Size(long jarg1, IntVectorPointer jarg1_);
  public final static native int IntVectorPointer_Value(long jarg1, IntVectorPointer jarg1_, long jarg2);
  public final static native long IntVectorPointer_Pointer(long jarg1, IntVectorPointer jarg1_);
  public final static native long new_StringPointer();
  public final static native void delete_StringPointer(long jarg1);
  public final static native long StringPointer_Pointer(long jarg1, StringPointer jarg1_);
  public final static native String StringPointer_ToString(long jarg1, StringPointer jarg1_);
  public final static native long new_IntVector__SWIG_0();
  public final static native long new_IntVector__SWIG_1(long jarg1);
  public final static native long IntVector_size(long jarg1, IntVector jarg1_);
  public final static native long IntVector_capacity(long jarg1, IntVector jarg1_);
  public final static native void IntVector_reserve(long jarg1, IntVector jarg1_, long jarg2);
  public final static native boolean IntVector_isEmpty(long jarg1, IntVector jarg1_);
  public final static native void IntVector_clear(long jarg1, IntVector jarg1_);
  public final static native void IntVector_add(long jarg1, IntVector jarg1_, int jarg2);
  public final static native int IntVector_get(long jarg1, IntVector jarg1_, int jarg2);
  public final static native void IntVector_set(long jarg1, IntVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_IntVector(long jarg1);
  public final static native long new_DoubleVector__SWIG_0();
  public final static native long new_DoubleVector__SWIG_1(long jarg1);
  public final static native long DoubleVector_size(long jarg1, DoubleVector jarg1_);
  public final static native long DoubleVector_capacity(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_reserve(long jarg1, DoubleVector jarg1_, long jarg2);
  public final static native boolean DoubleVector_isEmpty(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_clear(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_add(long jarg1, DoubleVector jarg1_, double jarg2);
  public final static native double DoubleVector_get(long jarg1, DoubleVector jarg1_, int jarg2);
  public final static native void DoubleVector_set(long jarg1, DoubleVector jarg1_, int jarg2, double jarg3);
  public final static native void delete_DoubleVector(long jarg1);
  public final static native long new_String2IntMap__SWIG_0();
  public final static native long new_String2IntMap__SWIG_1(long jarg1, String2IntMap jarg1_);
  public final static native long String2IntMap_size(long jarg1, String2IntMap jarg1_);
  public final static native boolean String2IntMap_empty(long jarg1, String2IntMap jarg1_);
  public final static native void String2IntMap_clear(long jarg1, String2IntMap jarg1_);
  public final static native int String2IntMap_get(long jarg1, String2IntMap jarg1_, String jarg2);
  public final static native void String2IntMap_set(long jarg1, String2IntMap jarg1_, String jarg2, int jarg3);
  public final static native void String2IntMap_del(long jarg1, String2IntMap jarg1_, String jarg2);
  public final static native boolean String2IntMap_has_key(long jarg1, String2IntMap jarg1_, String jarg2);
  public final static native void delete_String2IntMap(long jarg1);
  public final static native long new_Int2StringMap__SWIG_0();
  public final static native long new_Int2StringMap__SWIG_1(long jarg1, Int2StringMap jarg1_);
  public final static native long Int2StringMap_size(long jarg1, Int2StringMap jarg1_);
  public final static native boolean Int2StringMap_empty(long jarg1, Int2StringMap jarg1_);
  public final static native void Int2StringMap_clear(long jarg1, Int2StringMap jarg1_);
  public final static native String Int2StringMap_get(long jarg1, Int2StringMap jarg1_, int jarg2);
  public final static native void Int2StringMap_set(long jarg1, Int2StringMap jarg1_, int jarg2, String jarg3);
  public final static native void Int2StringMap_del(long jarg1, Int2StringMap jarg1_, int jarg2);
  public final static native boolean Int2StringMap_has_key(long jarg1, Int2StringMap jarg1_, int jarg2);
  public final static native void delete_Int2StringMap(long jarg1);
}
