/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.google.re2fj.wrapper;

public class Re2Set {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Re2Set(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Re2Set obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        re2fjJNI.delete_Re2Set(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Re2Set(Re2Options options, int anchor_id) {
    this(re2fjJNI.new_Re2Set(Re2Options.getCPtr(options), options, anchor_id), true);
  }

  public int Add(String pattern, SWIGTYPE_p_std__string error) {
    return re2fjJNI.Re2Set_Add(swigCPtr, this, pattern, SWIGTYPE_p_std__string.getCPtr(error));
  }

  public boolean Compile() {
    return re2fjJNI.Re2Set_Compile(swigCPtr, this);
  }

  public boolean Match(String text, IntVector v) {
    return re2fjJNI.Re2Set_Match(swigCPtr, this, text, IntVector.getCPtr(v), v);
  }

}
