/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.google.re2fj.wrapper;

public class StringPointer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringPointer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringPointer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        re2fjJNI.delete_StringPointer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringPointer() {
    this(re2fjJNI.new_StringPointer(), true);
  }

  public SWIGTYPE_p_std__string Pointer() {
    long cPtr = re2fjJNI.StringPointer_Pointer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public String ToString() {
    return re2fjJNI.StringPointer_ToString(swigCPtr, this);
  }

}
