/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.google.re2fj.wrapper;

public class SWIGTYPE_p_RE2__Options {
  private long swigCPtr;

  protected SWIGTYPE_p_RE2__Options(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_RE2__Options() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_RE2__Options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

